monitor.alsa.rules = [
  {
    matches = [ { device.name = "~alsa_card.usb-*" } ]
    actions = {
      update-props = {
        session.suspend-on-idle = false
        api.alsa.soft-volume     = true
        api.alsa.soft-mixer      = true
      }
    }
  }
]
